---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
      - "go"
      - "kind/chore"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/web"
    labels:
      - "dependencies"
      - "javascript"
      - "kind/chore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/testgrid/web"
    labels:
      - "dependencies"
      - "javascript"
      - "kind/chore"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
