apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: kurl-builtin
spec:
  collectors:
  - blockDevices:
      # cstor is enabled and not upgrade
      exclude: '{{kurl and (and .Installer.Spec.OpenEBS.Version .Installer.Spec.OpenEBS.IsCstorEnabled) (not .IsUpgrade) | not }}'

  analyzers:
  - blockDevices:
      # cstor is enabled and not upgrade
      includeUnmountedPartitions: true
      minimumAcceptableSize: 10737418240 # 1024 ^ 3 * 10, 10GiB
      exclude: '{{kurl and (and .Installer.Spec.OpenEBS.Version .Installer.Spec.OpenEBS.IsCstorEnabled) (not .IsUpgrade) | not }}'
      outcomes:
      - pass:
          when: ".* == 1"
          message: One available block device
      - pass:
          when: ".* > 1"
          message: Multiple available block devices
      - fail:
          message: No available block devices
