---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: $CONTOUR_HTTP_PORT
  - port: 443
    nodePort: $CONTOUR_HTTPS_PORT
