---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  ports:
    - name: http
      nodePort: $NGINX_HTTP_PORT
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      nodePort: $NGINX_HTTPS_PORT
      protocol: TCP
      targetPort: https
      appProtocol: https
