- name: "prometheus minimal k8s 1.25"
  installerSpec:
    kubernetes:
      version: "1.25.x"
    flannel:
      version: latest
    openebs:
      version: "3.3.0"
      isLocalPVEnabled: true
      localPVStorageClassName: default
    containerd:
      version: "latest"
    prometheus:
      version: "__testver__"
      s3Override: "__testdist__"
- name: "prometheus upgrade from 0.33.0"
  installerSpec:
    kubernetes:
      version: "1.21.x"
    flannel:
      version: latest
    rook:
      version: "1.10.x"
      isBlockStorageEnabled: true
    containerd:
      version: "latest"
    prometheus:
      version: "0.33.0"
  upgradeSpec:
    kubernetes:
      version: "1.23.x"
    flannel:
      version: latest
    rook:
      version: "1.10.x"
      isBlockStorageEnabled: true
    containerd:
      version: "latest"
    prometheus:
      version: "__testver__"
      s3Override: "__testdist__"
- name: "prometheus upgrade from latest"
  installerSpec:
    kubernetes:
      version: "1.25.x"
    flannel:
      version: latest
    openebs:
      version: "3.3.0"
      isLocalPVEnabled: true
      localPVStorageClassName: default
    containerd:
      version: "latest"
    prometheus:
      version: "latest"
  upgradeSpec:
    kubernetes:
      version: "1.25.x"
    flannel:
      version: latest
    openebs:
      version: "3.3.0"
      isLocalPVEnabled: true
      localPVStorageClassName: default
    containerd:
      version: "latest"
    prometheus:
      version: "__testver__"
      s3Override: "__testdist__"
- name: "prometheus with longhorn and containerd"
  installerSpec:
    kubernetes:
      version: "1.24.x"
    flannel:
      version: latest
    longhorn:
      version: "latest"
    containerd:
      version: "latest"
    prometheus:
      version: "__testver__"
      s3Override: "__testdist__"
- name: "prometheus minimal airgap"
  installerSpec:
    kubernetes:
      version: "1.24.x"
    flannel:
      version: latest
    rook:
      version: "1.7.x"
      isBlockStorageEnabled: true
    containerd:
      version: "latest"
    prometheus:
      version: "__testver__"
      s3Override: "__testdist__"
  airgap: true
