apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
metadata:
  name: kubeadm-cluster-configuration
apiServer:
  extraArgs:
    enable-admission-plugins: NodeRestriction
    kubelet-certificate-authority: /etc/kubernetes/pki/ca.crt
