installer:
  spec:
    kubernetes:
      version: 1.22.5
    containerd:
      version: latest
    prometheus:
      version: 0.46.0
output:
  - message: prometheus <= 0.49.0-17.1.3 is not compatible with kubernetes 1.22+
    field: spec.prometheus.version
    type: incompatibility
