name: daily-scan-images

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch: {}

jobs:
  build-matrix:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./bin/scan-images/
        run: npm install
      - id: set-matrix
        name: Build image matrix
        run: |
          OUTPUT=`./bin/scan-images/matrix.js`
          echo "::set-output name=matrix::$OUTPUT"

  scan-image:
    needs: build-matrix
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{fromJSON(needs.build-matrix.outputs.matrix)}}
      fail-fast: false
      max-parallel: 5
    steps:
      - name: "${{ matrix.addon }}:${{ matrix.version }} - ${{ matrix.name }} : Write Trivy ignore file"
        run: if [ -n '${{ matrix.trivyignore }}' ]; then echo '${{ matrix.trivyignore }}' | base64 -d > .trivyignore.rego ; fi
      - name: "${{ matrix.addon }}:${{ matrix.version }} - ${{ matrix.name }} : Scan image"
        id: scan
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: ${{ matrix.image }}
          exit-code: '1'
          vuln-type: 'os'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          ignore-policy: ${{ matrix.trivyignore && '.trivyignore.rego' }}
