name: testGrid-daily
on:
  schedule:
  - cron: "0 5 * * *"
  workflow_dispatch: {}

jobs:
  testgrid-daily:
    if: ${{ github.repository_owner == 'replicatedhq' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: pull tgrun image
      run: docker pull replicated/tgrun:latest

      # Run staging before production because the spec might use properties not yet present in production
    - name: testgrid-queue-staging
      env:
        TESTGRID_API_TOKEN: ${{ secrets.TESTGRID_PROD_API_TOKEN }}
      run: |
        docker run --rm -e TESTGRID_API_TOKEN -v `pwd`:/wrk -w /wrk \
          replicated/tgrun:latest queue --staging \
            --ref "STAGING-daily-$(date --utc +%FT%TZ)" \
            --spec ./testgrid/specs/full.yaml \
            --os-spec ./testgrid/specs/os-firstlast.yaml \
            --priority -1

    - name: testgrid-queue-prod
      env:
        TESTGRID_API_TOKEN: ${{ secrets.TESTGRID_PROD_API_TOKEN }}
      run: |
        docker run --rm -e TESTGRID_API_TOKEN -v `pwd`:/wrk -w /wrk \
          replicated/tgrun:latest queue \
            --ref "PROD-daily-$(date --utc +%FT%TZ)" \
            --spec ./testgrid/specs/full.yaml \
            --os-spec ./testgrid/specs/os-firstlast.yaml \
            --priority -2
