name: test-addon.yaml

on:
  workflow_call:
    inputs:
      addon:
        description: Add-on directory name
        required: true
        type: string
      version:
        description: Add-on version directory name
        required: true
        type: string
      prefix:
        description: Prefix for s3 asset and ref. For identification.
        type: string
  workflow_dispatch:
    inputs:
      addon:
        description: Add-on directory name
        required: true
      version:
        description: Add-on version directory name
        required: true
      prefix:
        description: Prefix for s3 asset and ref. For identification.

jobs:
  test-addon:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Tgrun Build
        working-directory: ./testgrid/tgrun
        run: make build-cli

      - name: Tgrun Queue
        id: queue
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          TESTGRID_API_TOKEN: ${{ secrets.TESTGRID_PROD_API_TOKEN }}
          S3_BUCKET: "kurl-sh"
          ADDON: ${{ inputs.addon }}
          VERSION: ${{ inputs.version }}
          PREFIX: ${{ inputs.prefix }}
        run: |
          source ./bin/test-addon-pr.sh
          run "$ADDON" "$VERSION" "$PREFIX"

      - name: Post TG URL
        uses: mshick/add-pr-comment@v1
        with:
          message: ${{ steps.queue.outputs.msg }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false
